#! /bin/sh

apt-get install python3 python3-pip
pip3 install selenium

echo "mejl?"
read mejl
echo "lozinka?"
read pasw
echo "MEJL ='$mejl'\nPASS = '$pasw'" > config.py

wget -N http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -P .
unzip chromedriver_linux64.zip
rm chromedriver_linux64.zip

mkdir /usr/share/fb_poruke1/
cp -t /usr/share/fb_poruke1 spamaj.py config.py chromedriver
echo "##spamovanje fb\nalias spamaj='/usr/share/fb_poruke1/spamaj.py'" >> ~/.bashrc

echo "Gotovo!"
